<?xml version="1.0" encoding="UTF-8"?>
<!--
 * SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
 * SPDX-License-Identifier: MIT
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.jcabi</groupId>
    <artifactId>parent</artifactId>
    <version>0.73.1</version>
  </parent>
  <groupId>com.github.fabriciofx</groupId>
  <artifactId>fake-logger</artifactId>
  <packaging>jar</packaging>
  <name>fake-logger</name>
  <version>1.0-SNAPSHOT</version>
  <description>A fake logger for tests</description>
  <url>https://github.com/fabriciofx/fake-logger</url>
  <inceptionYear>2025</inceptionYear>
  <organization>
    <name>fake-logger</name>
    <url>https://github.com/fabriciofx/fake-logger</url>
  </organization>
  <licenses>
    <license>
      <name>MIT</name>
      <url>https://github.com/fabriciofx/fake-logger/LICENSES/MIT.txt</url>
      <distribution>site</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>fabriciofx</id>
      <name>Fabrício Barros Cabral</name>
      <email>fabriciofx@gmail.com</email>
      <organization>fabriciofx</organization>
      <organizationUrl>https://github.com/fabriciofx</organizationUrl>
      <roles>
        <role>Architect</role>
        <role>Developer</role>
      </roles>
      <timezone>-3</timezone>
    </developer>
  </developers>
  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/fabriciofx/fake-logger/issues</url>
  </issueManagement>
  <scm>
    <connection>scm:git:git@github.com:fabriciofx/fake-logger.git</connection>
    <developerConnection>
      scm:git:git@github.com:fabriciofx/fake-logger.git
    </developerConnection>
    <url>https://github.com/fabriciofx/fake-logger</url>
  </scm>
  <distributionManagement>
    <site>
      <id>github-pages</id>
      <url>https://github.com/fabriciofx/fake-logger</url>
    </site>
  </distributionManagement>
  <properties>
    <maven.plugin.validation>VERBOSE</maven.plugin.validation>
    <github.repo>fabriciofx/cactoos-cache</github.repo>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>6.0.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.llorllale</groupId>
      <artifactId>cactoos-matchers</artifactId>
      <version>0.25</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.16.0</version>
        <configuration>
          <release>21</release>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.5.5</version>
        <configuration>
          <redirectTestOutputToFile>true</redirectTestOutputToFile>
          <systemPropertyVariables>
            <java.util.logging.config.file>
              src/test/resources/logging.properties
            </java.util.logging.config.file>
          </systemPropertyVariables>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.5.0</version>
        <configuration>
          <propertiesEncoding>UTF-8</propertiesEncoding>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.4.0</version>
        <executions>
          <execution>
            <id>artifact-sources</id>
            <configuration>
              <forceCreation>true</forceCreation>
            </configuration>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>qulice</id>
      <build>
        <plugins>
          <plugin>
            <groupId>com.qulice</groupId>
            <artifactId>qulice-maven-plugin</artifactId>
            <version>0.27.5</version>
            <configuration>
              <excludes combine.children="append">
                <exclude>checkstyle:/src/site/resources/.*</exclude>
                <exclude>findbugs:.*</exclude>
                <exclude>xml:.*</exclude>
              </excludes>
            </configuration>
            <executions>
              <execution>
                <id>qulice-check</id>
                <phase>verify</phase>
                <goals>
                  <goal>check</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
